### ISSUE TITLE
Modify train names 

### ISSUE THREAD

**Issue by memohk72** [opentransportro/cfr-gtfs-exporter#1]
![trains-name](https://user-images.githubusercontent.com/1998040/105153851-95c1a680-5b11-11eb-9223-bacdd7c52daf.png)

Change name of train from IR-N1766.3 to IR-N1766 (limit the name of trains to max 8 characters).

**Comment by vesavlad** [comment]
Naming will change as agreed from **IR-N1766.3** to **IR1766**

**Comment by memohk72** [comment]
Perfect :)
