### ISSUE TITLE
Remove the special character from train names

### ISSUE THREAD

**Issue by memohk72** [opentransportro/cfr-gtfs-exporter#2]
![trains-name2](https://user-images.githubusercontent.com/1998040/105154679-76774900-5b12-11eb-8208-2da2a231b8dc.png)

Remove the special character from train names and replace it with empty space.
E.g.: from IR-N1766 to IR N1766

**Comment by vesavlad** [comment]
As seen on #1 the name will no longer include -N or -% suffixes therefore more clean

**Comment by memohk72** [comment]
Perfect! Thank you. :)

**Comment by vesavlad** [comment]
CFR Călători opera până la data de 9 decembrie 2011 opt tipuri de trenuri atât pe teritoriul țării cât și în trafic internațional. Tipurile de trenuri ale CFR Călători erau:

    Personal (P), numerotate de la 2000 la 9999
    Accelerat (A), numerotate de la 1000 la 1999
    Rapid (R), numerotate de la 200 la 499, de la 600 la 999 si de la 10000 la 14999
    Rapid Internațional (RI), numerotat de la 300 la 499
    Inter City (IC), numerotate de la 500 la 599
    Euro Night (EN), cu aceleași tarife ca un rapid; la sfârșitul perioadei de existență a acestui tip de tren circula o singură pereche de trenuri EN, ele fiind clasificate ca rapidul 370/371 „Ister”, pe ruta–București Nord–Budapest Keleti)
    Euro City (EC), în această categorie fiind inclus EC 46/47 „Traianus” (care a circulat între Budapesta-București Nord, ruta lui fiind ulterior limitată și deviată la Budapesta-Timișoara)
    Special (S), numerotate de la S1 la S9

După data de 11 decembrie 2011, odată cu schimbarea mersului trenurilor și revenirea la organizarea pe 8 regionale de călători, rangurile trenurilor au devenit doar 3, modificare efectuată în urma acordurilor și armonizării cu practica mai multor companii feroviare europene.

    Regio (R)–fostele trenuri personale, oprește de regulă în toate stațiile și haltele de pe parcurs.
    InterRegio (IR)–fostele trenuri rapid și accelerat, care aveau anterior standarde similare de viteză, stații în care opresc și confort; trenurile IR opresc în stațiile mari și mijlocii de pe parcurs. Prețul este o medie între cele ale fostelor rapide și accelerate.
    InterCity (IC)–similar trenurilor anterioare cu același rang.

Din 2015 mai există doar trenuri Regio și InterRegio, trenurile IC fiind retrogradate la statutul de IR datorită imposibilității companiei de a asigura viteza minimă de 60 km/h.[4]

Ocazional, la trenurile cu parcurs noaptea, unde se adauga vagoane tip cuseta, trenurile devin **InterRegioNight** (**IRN**) 


Therefore N will be kept
